cargo-features = ["strip"]

[package]
name = "myip"
version = "0.1.0"
edition = "2018"

[dependencies]
curl = "0.4.36"

[profile.release]
strip = "symbols"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
